eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8761/eureka/
      
server:
  port: 8803
  
spring:
  application:
    name: service-wallet
  dubbo:
    application:
      name: dubbo-wallet
    registry: 
      address: zookeeper://172.16.2.176:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: com.example.demo
  zipkin:
    base-url: http://172.16.2.176:9411
    
    