eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
      
server:
  port: 8803
  
spring:
  application:
    name: service-wallet
  dubbo:
    application:
      name: dubbo-wallet
    registry: 
      address: zookeeper://peer1:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: com.example.demo
  zipkin:
    base-url: http://peer1:9411
    
    